In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from data_processing import daily_stock_std
from robust_filter import placeholder_filter

In [2]:
ROOT = Path.cwd()
PROJECT_ROOT = ROOT
DATA_DIR = PROJECT_ROOT / "data"
DATA_PATH = DATA_DIR / "bin201901.csv"
DATA_PATH

PosixPath('/Users/elsaemiliabodle/VSCodeProjects/robust-filtering/data/bin201901.csv')

In [3]:
df = pd.read_csv(DATA_PATH)

In [4]:
df_subset = df[df["stock"] == "AAPL"]
df_subset.head()

,date,time,stock,trade,orderFlow,hidden,auction,mid,midEnd,spread,effSpread,lobImb,effLobImb,trdLiq,ofLiq,depth,nbEvents,nbHidden,nbTrades
6627,2019-01-02,09:30:00,AAPL,-11855,-14141,12397,419249,154.915,154.755,0.055,0.156354,0.866667,0.261039,18657,68751,277.6250,8,1,2
6628,2019-01-02,09:30:10,AAPL,527,3346,4579,0,154.640,154.645,0.070,0.055760,0.000000,-0.659986,11359,42698,313.8571,7,1,2
6629,2019-01-02,09:30:20,AAPL,-2979,7161,1765,0,154.595,154.605,0.045,0.041798,0.333333,-0.010202,6573,78475,337.6250,8,1,2
6630,2019-01-02,09:30:30,AAPL,5120,12162,1663,0,154.600,154.620,0.010,0.015000,0.666667,0.703877,7322,106242,897.1111,9,1,2
6631,2019-01-02,09:30:40,AAPL,8889,29297,1038,0,154.885,154.875,0.035,0.029257,0.760000,0.640284,12651,126539,831.2500,8,1,2

In [8]:
std_df = daily_stock_std(df_subset, date_col="date", stock_col="stock", value_col="mid")
std_df.head(10)

         date stock   mid_std
0  2019-01-02  AAPL  1.120240
1  2019-01-03  AAPL  0.911967
2  2019-01-04  AAPL  0.984060
3  2019-01-07  AAPL  0.583499
4  2019-01-08  AAPL  0.818250
5  2019-01-09  AAPL  0.486091
6  2019-01-10  AAPL  0.608748
7  2019-01-11  AAPL  0.427133
8  2019-01-14  AAPL  0.246215
9  2019-01-15  AAPL  0.613424

In [ ]:
placeholder_filter()